default_password: "12345678"
search_field:
  user: "name_cont"
  category: "name_cont"
  question: "content_cont"
size_avatar_list: "50x50"
size_profile: "50x50"
size: 9
size_avatar: "200x200"
size_avatar_activity: "30x30"
time_format: "%d/%m/%Y"
date_time_format: "%d/%m/%Y %H:%M:%S"
lesson_size: 2
duration: 200
relation:
  following: "following"
  followers: "followers"
label:
  label_testing: "label label-warning"
  label_init: "label label-default"
  label_checked: "label label-success"
btn:
  btn_start: "btn btn-primary"
  btn_view: "btn btn-success"
